name: CI

on:
  push:
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
  pull_request:
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ['24.x']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm install
      - name: Compile TypeScript
        run: npm run compile
      - name: Run headless tests
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test
